import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HeroSection1 from "../components/HeroSection1";
import Services from "./Services";
import Contact from "../components/Contact";
import Projects from "./Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection1 />
      <Projects />
      <Services />
      <Contact />
      <Footer />
    </>
  );
}
